package pixel

import (
	"bnd/input"
	"github.com/faiface/pixel/pixelgl"
)

func toPixel(key input.Key) pixelgl.Button {
	switch key {
	case input.KeyW:
		return pixelgl.KeyW
	case input.KeyD:
		return pixelgl.KeyD
	case input.KeyS:
		return pixelgl.KeyS
	case input.KeyA:
		return pixelgl.KeyA
	case input.KeyEsc:
		return pixelgl.KeyEscape
	case input.KeyEnter:
		return pixelgl.KeyEnter
	case input.KeySpace:
		return pixelgl.KeySpace
	case input.KeyLeft:
		return pixelgl.KeyLeft
	case input.KeyRight:
		return pixelgl.KeyRight
	case input.KeyUp:
		return pixelgl.KeyUp
	case input.KeyDown:
		return pixelgl.KeyDown
	case input.KeyQ:
		return pixelgl.KeyQ
	case input.KeyE:
		return pixelgl.KeyE
	case input.KeyR:
		return pixelgl.KeyR
	case input.KeyT:
		return pixelgl.KeyT
	case input.KeyY:
		return pixelgl.KeyY
	case input.KeyU:
		return pixelgl.KeyU
	case input.KeyI:
		return pixelgl.KeyI
	case input.KeyO:
		return pixelgl.KeyO
	case input.KeyP:
		return pixelgl.KeyP
	case input.KeyF:
		return pixelgl.KeyF
	case input.KeyG:
		return pixelgl.KeyG
	case input.KeyH:
		return pixelgl.KeyH
	case input.KeyJ:
		return pixelgl.KeyJ
	case input.KeyK:
		return pixelgl.KeyK
	case input.KeyL:
		return pixelgl.KeyL
	case input.KeyZ:
		return pixelgl.KeyZ
	case input.KeyX:
		return pixelgl.KeyX
	case input.KeyC:
		return pixelgl.KeyC
	case input.KeyV:
		return pixelgl.KeyV
	case input.KeyB:
		return pixelgl.KeyB
	case input.KeyN:
		return pixelgl.KeyN
	case input.KeyM:
		return pixelgl.KeyM
	case input.Key1:
		return pixelgl.Key1
	case input.Key2:
		return pixelgl.Key2
	case input.Key3:
		return pixelgl.Key3
	case input.Key4:
		return pixelgl.Key4
	case input.Key5:
		return pixelgl.Key5
	case input.Key6:
		return pixelgl.Key6
	case input.Key7:
		return pixelgl.Key7
	case input.Key8:
		return pixelgl.Key8
	case input.Key9:
		return pixelgl.Key9
	case input.Key0:
		return pixelgl.Key0
	case input.KeyLShift:
		return pixelgl.KeyLeftShift
	case input.KeyRShift:
		return pixelgl.KeyRightShift
	case input.KeyLControl:
		return pixelgl.KeyLeftControl
	case input.KeyRControl:
		return pixelgl.KeyRightControl
	case input.KeyLAlt:
		return pixelgl.KeyLeftAlt
	case input.KeyRAlt:
		return pixelgl.KeyRightAlt
	case input.KeyCapsLock:
		return pixelgl.KeyCapsLock
	case input.KeyTab:
		return pixelgl.KeyTab
	case input.KeyBackspace:
		return pixelgl.KeyBackspace
	default:
		return pixelgl.KeyUnknown
	}
}
